// Generated by diesel_ext

use diesel::{Insertable, Queryable};
use serde::{Deserialize, Serialize};

#[derive(Queryable, Debug, Serialize)]
pub struct Cat {
    pub id: i32,
    pub name: String,
    pub image_path: String,
}

#[derive(Insertable, Serialize, Deserialize)]
#[diesel (table_name = crate::schema::cats)]
pub struct NewCat {
    // id will be added by the database
    pub name: String,
    pub image_path: String,
}
